test

diff --git a/src/apkinfo b/src/apkinfo
--- a/src/apkinfo
+++ b/src/apkinfo
@@ -1,7 +1,7 @@
-#!/bin/bash -x
+#!/bin/bash
 # ****************************************************************************************
 #  [脚本标题描述]
-#  version    : 1.0.0
+#  version    : 0.0.1
 #  author     : DavidZou -- wearecisco@gmail.com
 #  date       : 2017.05.07
 #
@@ -14,6 +14,10 @@
 #  [环境配置]:
 #
 # ****************************************************************************************
+
+# 命令版本
+APKINFO_VERSION="0.0.1"
+BREW_HOME="/usr/local/Cellar/apkinfo/${APKINFO_VERSION}/"
 
 ######################
 # 检测系统是否配置了aapt命令
@@ -61,21 +65,24 @@ function getValueMeta(){
 # ====================
 # 环境参数及类管理
 # ====================
+# 如果配置文件存在的则读取配置文件，deploy的和brew安装的区别就是不会创建文件夹
+if [ ! -d ~/.apkinfo ] ; then
+    mkdir -p ~/.apkinfo
+    echo "apkinfo.home=${BREW_HOME}" > ~/.apkinfo/apkinfo.rc
+    ROOT=${BREW_HOME}
+else
+    # 读取命令所在的目录
+    if [ ! -f ~/.apkinfo/apkinf.rc ] ; then
+        echo "[Error] Install failed. To retry invoked deploy.sh or install by brew."
+        exit 1
+    fi
+    ROOT=`cat ~/.apkinfo/apkinfo.rc | grep apkinfo | cut -d = -f2-`
+fi
+
+echo ${ROOT}
+
 
 echo "Hello erery body!!!"
 
 check_command_aapt
 echo ${AAPT_HOME}
-
-#if [ $1 =~ "apk" ] ; then
-#    # 直接执行解析，默认显示数据
-#    echo "aok"
-#fi
-
-echo "`pwd`"
-echo ${pwd}
-echo ${0}
-echo ${pwd}/${0}
-
-PATH=`find -L ${0} -name "tools"`
-echo ${PATH}
